f = open('myfile1.txt', 'a+')
print('Before reading the reference point is ',f.tell())
print(f.read())
print('After reading the reference point is ',f.tell()) 

print('Reading from a particular reference point ')
f.seek(-3,2)
print(f.tell())
f.write('abc')
print(f.read()) 
f.close()
# f = open('myfile1.txt', 'a')
# f.write('abc')
# f.close()